name: CHANGELOG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version')"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: php-parallel-lint/php-var-dump-check, parallel-lint, cs2pr, phpcs

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Run PHPCS
        run: phpcs -q --report=checkstyle --standard=codesniffer/ruleset.xml --extensions=php --ignore=*/tx/*,*/vendor/* . | cs2pr --graceful-warnings

      - name: Run Parallel Lint
        run: parallel-lint --exclude vendor/ .

      - name: Run VarDump Check
        run: var-dump-check --extensions php --tracy --exclude vendor/ .

      - name: Run autotranslator
        run: |
          php ./.tx/autotranslator.php fr_FR it_IT ${{ secrets.GOOGLE_API_TRANSLATE }}
          php ./.tx/autotranslator.php fr_FR en_US ${{ secrets.GOOGLE_API_TRANSLATE }}
          php ./.tx/autotranslator.php fr_FR es_ES ${{ secrets.GOOGLE_API_TRANSLATE }}
          php ./.tx/autotranslator.php fr_FR de_DE ${{ secrets.GOOGLE_API_TRANSLATE }}
          php ./.tx/autotranslator.php fr_FR pt_PT ${{ secrets.GOOGLE_API_TRANSLATE }}
          php ./.tx/autotranslator.php fr_FR pl_PL ${{ secrets.GOOGLE_API_TRANSLATE }}

      - name: Run changelog
        run: npx lerna-changelog --from=v0.0.0 > ChangeLog.md
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        uses: frederic34/github-dolibarr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: frederic34
          RELEASE_BRANCH: main
          MODULE: easydocgenerator
          CLASSNAME: Easydocgenerator
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: none
          INITIAL_VERSION: v0.0.0
          VERBOSE: true

      - name: Zip Folder
        run: |
          composer update --no-dev
          mkdir -p build/easydocgenerator
          rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='.tx/' --exclude='build/' --exclude='codesniffer/' . ./build/easydocgenerator

      - name: Create release zip
        run: |
          cd build
          rm -f module_easydocgenerator-${{ env.module_version }}.zip
          zip -r module_easydocgenerator-${{ env.module_version }}.zip easydocgenerator

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump version #none
